# Generated by Django 4.0.4 on 2022-06-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimg',
            name='user_img',
        ),
    ]
