# Generated by Django 4.0.4 on 2022-06-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_remove_profileimg_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimg',
            name='image',
        ),
    ]
