# Generated by Django 4.0.4 on 2022-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_profileimg_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='profileimg',
            name='user',
        ),
        migrations.AddField(
            model_name='profileimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
