# Generated by Django 4.0.4 on 2022-06-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0012_alter_profileimg_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
