# Generated by Django 4.0.4 on 2022-06-27 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimg',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profileimg',
            name='user_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
