# Generated by Django 4.0.4 on 2022-06-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0015_alter_profileimg_image_alter_profileimg_user_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
