# Generated by Django 4.0.4 on 2022-06-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
