# Generated by Django 4.0.4 on 2022-06-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0019_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
