# Generated by Django 4.0.4 on 2022-06-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0021_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
