# Generated by Django 4.0.4 on 2022-07-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_alter_profileimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimg',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profileimg',
            name='user_pic',
        ),
    ]
