# Generated by Django 4.0.4 on 2022-07-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_remove_profileimg_image_remove_profileimg_user_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
