# Generated by Django 4.0.4 on 2022-07-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
