# Generated by Django 4.0.4 on 2022-07-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
