# Generated by Django 4.0.4 on 2022-07-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimg',
            name='image',
            field=models.ImageField(blank=True, default='/static/avatar.png', upload_to='profiles', verbose_name='profile'),
        ),
    ]
