# Generated by Django 4.0.4 on 2022-07-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_alter_profileimg_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
