# Generated by Django 4.0.4 on 2022-07-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
