# Generated by Django 4.0.4 on 2022-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0015_rename_user_pic_profileimg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimg',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='profiles'),
        ),
    ]
