# Generated by Django 4.0.4 on 2022-07-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0016_alter_profileimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimg',
            name='age',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profileimg',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
