# Generated by Django 4.0.4 on 2022-07-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0019_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.RemoveField(
            model_name='profileimg',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
