# Generated by Django 4.0.4 on 2022-07-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familypost',
            name='user',
        ),
        migrations.DeleteModel(
            name='FollowersCount',
        ),
        migrations.RemoveField(
            model_name='frindspost',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileimg',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyPost',
        ),
        migrations.DeleteModel(
            name='FrindsPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ProfileImg',
        ),
    ]
