# Generated by Django 4.0.4 on 2022-07-13 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0024_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slag',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='familypost',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='famliyposts'),
        ),
        migrations.AlterField(
            model_name='frindspost',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='frindsposts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='profileimg',
            name='contory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
